{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\"},ns)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "query_result({job=\"$job_name\", __name__=~\"aerospike_laten.*\", cluster_name=~\"$cluster|$^\",  })"
    }
   },
   { "name": "latencytimeunit", "label": "Latency Time Unit", "query": { "query": "metrics(aerospike_latencies_)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Name",
   "type": "stat",
   "description": "Cluster size",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "#sum(aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\"})\ncount_values by (cluster_name) (\"cluster\",aerospike_node_stats_cluster_size{cluster_name=\"$cluster\"}) ",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Index used (bytes) (total)",
   "type": "stat",
   "description": "Displays sum of all device or memory used by index, sindex and set-index",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "sum(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Used Bytes"
    }
   ]
  },
  {
   "title": "Data (bytes) (total)",
   "type": "stat",
   "description": "Displays sum of all device or memory used by data (without index) and the sum of allocated bytes",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\n) ",
     "legendFormat": "Used (Device/PMEM) (pre 7x)"
    },
    {
     "expr": "sum(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "stat",
   "description": "Cluster size",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "#sum(aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\"})\ncount_values (\"size\", (aerospike_node_stats_cluster_size{cluster_name=\"$cluster\"}) )",
     "legendFormat": "{{size}}"
    }
   ]
  },
  {
   "title": "Percentiles reads",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(ns) (histogram_quantile(0.95, aerospike_latencies_read_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p95 ${latencytimeunit}"
    },
    {
     "expr": "avg by(ns) (histogram_quantile(0.99, aerospike_latencies_read_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p99 ${latencytimeunit}"
    },
    {
     "expr": "avg by(ns) (histogram_quantile(0.999, aerospike_latencies_read_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p99.9 ${latencytimeunit}"
    },
    {
     "expr": "avg by(ns) (histogram_quantile(0.9999, aerospike_latencies_read_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p99.99 ${latencytimeunit}"
    }
   ]
  },
  {
   "title": "Percentiles writes",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(ns) (histogram_quantile(0.95, aerospike_latencies_write_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p95 ${latencytimeunit}"
    },
    {
     "expr": "avg by(ns) (histogram_quantile(0.99, aerospike_latencies_write_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p99 ${latencytimeunit}"
    },
    {
     "expr": "avg by(ns) (histogram_quantile(0.99, aerospike_latencies_write_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p99.9 ${latencytimeunit}"
    },
    {
     "expr": "avg by(ns) (histogram_quantile(0.99, aerospike_latencies_write_us_bucket{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "p99.99 ${latencytimeunit}"
    }
   ]
  },
  {
   "title": "Master Objects (total)",
   "type": "stat",
   "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Master"
    }
   ]
  },
  {
   "title": "Client Reads (TPS) (rate) (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job, cluster_name) (rate(aerospike_namespace_client_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{cluster_name}}: Total"
    }
   ]
  },
  {
   "title": "Client Writes (TPS) (rate) (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (job, cluster_name) (rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{cluster_name}}: Total"
    }
   ]
  }
 ]
}